// dashboard/src/components/core/footer.vue
<template>
  <n-space align="center" justify="space-between">
    <span>
      Source code at <a href="https://www.github.com/infinimesh/infinimesh" target="_blank">
        <strong>GitHub</strong>
      </a> ©2020-2022
    </span>
    <span>infinimesh {{ tag }}</span>
    <span></span>
  </n-space>
</template>

<script setup>
import { NSpace } from "naive-ui";

const tag = "development"
</script>

// frontend/src/app/theme/components/footer/footer.component.ts
import {Component} from '@angular/core';

@Component({
  selector: 'ngx-footer',
  styleUrls: ['./footer.component.scss'],
  template: `
    <span>©2019 — <strong>infinimesh, inc</strong> - source code at <a
      href="https://www.github.com/infinimesh/infinimesh" target="_new"><strong
      style="color: white;">GitHub</strong></a></span>
  `,
})
export class FooterComponent {
}
